#------------------------------------------------------------------------------
# Name:         schema.py
# Purpose:      The AT's Schema information for PloneFormMailer
#
# Author:       Jens Klein <jens.klein@jensquadrat.de>
# generated by: ArchGenXML Version 0.9.14 http://sf.net/projects/archetypes/
#
# RCS-ID:       $Id: schema.py,v 1.7 2004/10/20 20:17:06 dreamcatcher Exp $
# Copyright:    (c) 2004 by jens quadrat GbR, Germany
# Licence:      GNU General Public Licence (GPL) Version 2 or later
#------------------------------------------------------------------------------

from config import *
if HAS_LINGUA_PLONE:
    from Products.LinguaPlone.public import *
else:
    from Products.Archetypes.public import *

# for PloneFormMailer we want to have the description in the edit view
# just like CMF
PFMschema = BaseSchema.copy()
PFMschema['description'].isMetadata = False
PFMschema['description'].schemata = 'default'

PFMschema+= Schema((
    #name of the recipient
    StringField('recipient_name',
        widget=StringWidget(description = 'The full name of the recipient '
            'of the mailed form. TALES Expression. If you don\'t know '
            'TALES expressions just enter string:YOURTEXT.',
            description_msgid = "help_formmailer_recipient_fullname",
            label = 'Recipient\'s full name',
            label_msgid = "label_formmailer_recipient_fullname",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        validators=('talesvalidator',),
        schemata='Mail Header',
        required=1,
    ),

    #e-mail adress of the recipient of the form-data
    StringField('recipient_email',
        widget=StringWidget(description = 'The recipients e-mail address. '
            'TALES Expression. If you don\'t know TALES expressions just '
            'enter string:YOURTEXT.',
            description_msgid = "help_formmailer_recipient_email",
            label = 'Recipient\'s e-mail address',
            label_msgid = "label_formmailer_recipient_email",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Header',
        validators=('talesvalidator',),
        required=1
    ),

    #additional recipients email-adresses by CC
    LinesField('cc_recipients',
        widget=LinesWidget(
            description = 'E-mail addresses which receive a carbon copy. '
            'TALES Expression. If you don\'t know TALES expressions just '
            'enter string:YOURTEXT.',
            description_msgid = "help_formmailer_cc_recipients",
            label = 'Cc recipients',
            label_msgid = "label_formmailer_cc_recipients",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Header',
        validators=('talesvalidator',)
    ),


    #additional recipients email-adresses by BCC
    LinesField('bcc_recipients',
        widget=LinesWidget(
            description = 'E-mail addresses which receive a blind carbon copy. '
            'TALES Expression. If you don\'t know TALES expressions just '
            'enter string:YOURTEXT.',
            description_msgid = "help_formmailer_bcc_recipients",
            label = 'Bcc recipients',
            label_msgid = "label_formmailer_bcc_recipients",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Header',
        validators=('talesvalidator',)
    ),

    #header lines in formatting KEY: VALUE
    LinesField('additional_headers',
        widget=LinesWidget(description = 'Additional e-mail-header lines. '
            'Only fill in if you aware of RFC822.',
            description_msgid = "help_formmailer_additional_headers",
            label = 'Additional headers',
            label_msgid = "label_formmailer_additional_headers",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Header'
    ),

    #subject of the message
    StringField('subject',
        default = default_mailtemplate_subject,
        widget=StringWidget(description = 'Subject line of message. '
            'TALES Expression. If you don\'t know TALES expressions just '
            'enter string:YOURTEXT.',
            description_msgid = "help_formmailer_subject",
            label = 'Subject',
            label_msgid = "label_formmailer_subject",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        validators=('talesvalidator',),
        schemata='Mail Message'
    ),

    #text introduces the body before field-listing starts
    TextField('body_pre',
        widget=TextAreaWidget(description = 'Text prepended to fields listed '
            'in mail-body',
            description_msgid = "help_formmailer_body_pre",
            label = 'Body (prepended)',
            label_msgid = "label_formmailer_body_pre",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Message'
    ),

    #text in e-mail after field list
    TextField('body_post',
        widget=TextAreaWidget(description = 'Text appended to fields listed '
            'in mail-body',
            description_msgid = "help_formmailer_body_post",
            label = 'Body (appended)',
            label_msgid = "label_formmailer_body_post",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Message'
    ),

    #text used as the footer of e-mail (do not include delimiter)
    TextField('body_footer',
        widget=TextAreaWidget(description = 'Text used as the footer at '
            'bottom, delimited from the body by a dashed line.',
            description_msgid = "help_formmailer_body_footer",
            label = 'Body (footer)',
            label_msgid = "label_formmailer_body_footer",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Mail Message'
    ),

    #text introduces the body before field-listing starts
    TextField('body_pt',
        default = default_mailtemplate_body,
        default_content_type='application/xml+xhtml',
        default_output_type='text/plain',
        widget=TextAreaWidget(description = 'This is a Zope Page Template '
            'used for rendering of the mail-body. You don\'t need to modify '
            'it, but if you know TAL (Zope\'s Template Attribute Language) '
            'you have the full power to customize your outgoing mails.',
            description_msgid = "help_formmailer_body_pt",
            label = 'Mail-Body Template',
            label_msgid = "label_formmailer_body_pt",
            i18n_domain='pfm',
            rows = 30,
        ),
        languageIndependent=1,
        validators=('zptvalidator',),
        schemata='Template'
    ),
    StringField('body_type',
        default='text/html',
        widget=StringWidget(description = 'Set the mime-type of the mail-body. '
            'Change this setting only if you know exactly what you are doing. '
            'Leave it blank for default behaviour.',
            description_msgid = "help_formmailer_body_type",
            label = 'Mail-Body Type',
            label_msgid = "label_formmailer_body_type",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Template'
    ),

    #text prepended to list of fields
    TextField('form_pre',
        widget=RichWidget(description = "Text prepended to the web-form.",
            description_msgid = "help_formmailer_form_pre",
            label = "Text (prepended)",
            label_msgid = "label_formmailer_form_pre",
            i18n_domain='pfm',
            rows = 12
        ),
        default_content_type='text/structured',
        allowable_content_types=('text/structured',
                                'text/restructured',
                                'text/html',
                                'text/plain'),
        schemata='Form',
        default_output_type='text/html'
    ),
    #text appended to list of fields
    TextField('form_post',
        widget=TextAreaWidget(description = "Text appended to the web-form.",
            description_msgid = "help_formmailer_form_post",
            label = "Text (appended)",
            label_msgid = "label_formmailer_form_post",
            i18n_domain='pfm',
            rows = 12),
        default_content_type='text/structured',
        allowable_content_types=('text/structured',
                                'text/restructured',
                                'text/html',
                                'text/plain'),
        schemata='Form',
        default_output_type='text/html'
    ),


    #label for send button
    LinesField('form_buttons',
        widget=LinesWidget(description = 'Definition of the buttons. '
            'format: value|name|type|css-class.',
            description_msgid = "help_formmailer_form_buttons",
            label = 'Buttons',
            label_msgid = "label_formmailer_form_button_submit",
            i18n_domain='pfm',
        ),
        default=("""Submit|submit|submit|context""",
                 """Reset|reset|reset|standalone"""),
        schemata='Form',
        required=1,

    ),
    #gpg key-id
    StringField('gpg_keyid',
        widget=StringWidget(description = 'Give your key-id, e-mail or '
            'whatever works to match a public key from current keyring. '
            'It will be used to encrypt the '
            'message body. You need to have a working "GNU Privacy Guard" binary '
            'installed on the machine running zope! Test this feature before going public!',
            description_msgid = "help_formmailer_key_id",
            label = 'Key-Id',
            label_msgid = "label_formmailer_key_id",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Encryption'
    ),

##        #gpg keyserver
##        StringField('gpg_keyserver',
##            widget=StringWidget(description = 'Name a Keyserver, where the '
##                'above key can be found. Not needed if it is already in current'
##                'keyring or a public key is given',
##                description_msgid = "help_formmailer_gpg_keyserver",
##                label = 'Keyserver',
##                label_msgid = "label_formmailer_gpg_keyserver",
##            ),
##            schemata='Encryption'
##        ),
##
##
##        #gpg public key
##        TextField('gpg_public',
##            widget=TextAreaWidget(description = 'Paste your GPG/PGP public key in '
##                'here.',
##                description_msgid = "help_formmailer_gpg_public",
##                label = "Public Key",
##                label_msgid = "label_formmailer_gpg_public",
##                rows = 12),
##            default_content_type='text/plain',
##            allowable_content_types=('text/plain'),
##            schemata='Encryption',
##            default_output_type='text/html'
##        ),

    #action to be executed after successful validation
    StringField('cpyaction',
        widget=StringWidget(description = 'Set an alternate controller '
            'python script (cpy). Change this setting only if you know '
            'exactly what you are doing. Leave it blank for default behaviour.',
            description_msgid = "help_formmailer_cpyaction",
            label = 'Controller Script',
            label_msgid = "label_formmailer_cpyaction",
            i18n_domain='pfm',
        ),
        languageIndependent=1,
        schemata='Controller'
    ),

    #title of 'Sent Response'
    StringField('sent_title',
        widget=StringWidget(description = 'The title of the page displayed '
            'after successful sending. If left blank the primary title '
            'field is used.',
            description_msgid = "help_formmailer_sent_title",
            label = 'Title (sent page)',
            label_msgid = "label_formmailer_sent_title",
            i18n_domain='pfm',
        ),
        schemata='Sent Response'
    ),

    #message for 'Sent Response'
    TextField('sent_message',
        widget=RichWidget(description = 'The message of the page displayed '
            'after successful sending.',
            description_msgid = "help_formmailer_sent_msg",
            label = 'Message (sent page)',
            label_msgid = "label_formmailer_sent_msg",
            i18n_domain='pfm',
        ),
        default_content_type='text/structured',
        allowable_content_types=('text/structured',
                                'text/restructured',
                                'text/html',
                                'text/plain'),
        schemata='Sent Response',
        default_output_type='text/html'
    ),

    #ignore sent_title, sent_message and redirect to another page
    StringField('sent_redirect',
        widget=StringWidget(description = 'Redirect to a custom page '
            'is possible too (instead of standard sent page).'
            'TALES Expression. If you don\'t know TALES expressions just '
            'enter string:YOURTEXT.',
            description_msgid = "help_formmailer_sent_redirect",
            label = 'Redirect to (sent)',
            label_msgid = "label_formmailer_sent_redirect",
            i18n_domain='pfm',
        ),
        validators=('talesvalidator',),
        schemata='Sent Response'
    ),
),
)
