all: plonecollectorng-plone-de.mo plonecollectorng-de.mo


plonecollectorng-de.mo: plonecollectorng-de.po
	msgfmt -o plonecollectorng-de.mo plonecollectorng-de.po

plonecollectorng-plone-de.mo: plonecollectorng-plone-de.po
	msgfmt -o plonecollectorng-plone-de.mo plonecollectorng-plone-de.po

clean:
	rm *.mo
