all: plonecollectorng.mo plonecollectorng-de.mo

plonecollectorng.mo: plonecollectorng.pot
	msgfmt -o plonecollectorng.mo plonecollectorng.pot

plonecollectorng-de.mo: plonecollectorng-de.po
	msgfmt -o plonecollectorng-de.mo plonecollectorng-de.po
